### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by shubham1172** [vpython/glowscript#13]
I have been interested in using your rendering engine for a dummy physics engine I have been developing, but I cannot find any documentation. I can see examples and tutorials for beginners, but I am looking for a full reference manual like this - [Unity docs](https://docs.unity3d.com/Manual/index.html).

**Comment by BruceSherwood** [comment]
There isn't a VPython reference manual in the style of Unity docs, but there is a full reference manual by clicking "Help" at glowscript.org, or going directly to 

    https://www.glowscript.org/docs/VPythonDocs/index.html

Use the pull-down menus "Choose a 3D object" for the graphics primitives, "Work with 3D objects" for additional functionality such as graphs and widgets, or "Canvases/Events" for setting up 3D canvases and handling mouse and keyboard events.

**Comment by shubham1172** [comment]
Awesome! Looks good. Thanks 😄

**Comment by BruceSherwood** [comment]
Can you reconstruct how/why you hadn't found the documentation? Is there something wrong or missing from the Help at glowscript.org? Maybe I could fix something.

**Comment by shubham1172** [comment]
It was my bad, I couldn't figure out that the documentation was lying there all the time in the dropdowns. However, it would certainly be easier on the eye if the docs were spread out in some wiki fashion with a table of contents and a nice navigation bar. Example - http://www.panda3d.org/manual/
