### ISSUE TITLE
Is there a way to prevent glowscript buttons from calling a function multiple times when clicked?

### ISSUE THREAD

**Issue by Suhas-13** [vpython/glowscript#149]
As per the title. When a button is clicked it will call the method that is bound, regardless of whether it is already running, is there a way to stop the method from running first before calling it again? Currently, I am using a solution that involves setting a boolean that will be checked by the method and will cause it to break when set to true.

**Comment by BruceSherwood** [comment]
Using a boolean is certainly appropriate. Another option is seen in this comment in the Help for "Mouse Events":

Suppose you executed scene.bind('mousedown mousemove', Drag), but now you no longer want to send mousemove events to that function. Do this:

scene.unbind('mousemove', Drag)
