### ISSUE TITLE
Line numbers are not deleted

### ISSUE THREAD

**Issue by rodigu** [vpython/glowscript#158]
The line number of a new line will stay on even after the line it refers to is deleted.

**Comment by BruceSherwood** [comment]
?? I don't understand. If I erase what's on line 15, of course the line number remains, with a blank line to the right of the line number. For the line number to disappear requires selecting from the end of the previous line to the end of the line to be deleted.

**Comment by rodigu** [comment]
This doesn't happen for me when I first open a project to edit it.

You can see it happening the following video:
![https://user-images.githubusercontent.com/58960796/141353685-8321dea6-4179-449c-998c-6d49430dbc62.mp4]()
In it, I press enter a couple of times, creating new lines. Then I press backspace, deleting those lines. The line numbers are not updated.
Only when I press enter again, creating a new line, line numbers update.
The issue does not persist after the lines are updated.

**Comment by BruceSherwood** [comment]
Ah. Thanks. I hadn't noticed that. Presumably a failing of the Ace editor.
