### ISSUE TITLE
poly2tri.js overwrites DOM Node Interface

### ISSUE THREAD

**Issue by a3626a** [vpython/glowscript#160]
https://github.com/vpython/glowscript/blob/c65dabfa081f71750bbc4f80da7fc0cfa331980b/lib/opentype/poly2tri.js#L43-L68

Above `Node` definition overwrites [DOM Node Interface](https://developer.mozilla.org/en-US/docs/Web/API/Node), and breaks several basic DOM functionalities. (Check this [issue](https://github.com/vpython/vpython-jupyter/issues/194))

I found that simpe renaming strategy works, but I cannot recommend this for the solution. Because `poly2tri` has original implementation, and it is better to keep them in sync.

I think using original poly2tri implementation could be possible. Because jupyter extension environment has been changed a lot for 5 years. I have not tested this.

**Comment by BruceSherwood** [comment]
I've gone ahead and changed Node -> PolyNode in that font file. I'm not concerned about making this change, as the font file is old and stable. Thanks much for your help!

**Comment by a3626a** [comment]
I found that this commit(released as jupyterlab-vpython 3.1.3) successfully fixed the issue.
Thank you.

https://github.com/vpython/glowscript/commit/8eec81c33b6a178526b142878567aec8f8b6b882
