### ISSUE TITLE
How to sort nested list in web vpython ?

### ISSUE THREAD

**Issue by joejoe2** [vpython/glowscript#164]
I have read the doc of [rapydscript-ng](https://github.com/kovidgoyal/rapydscript-ng) and use pysort() for python sorting. But this is not work for nested list. 

You can see the example at [here](https://www.glowscript.org/#/user/7013601/folder/MyPrograms/program/Print).

**Comment by BruceSherwood** [comment]
Thanks for the report. When I run your code in the RapydScript-NG REPL (https://sw.kovidgoyal.net/rapydscript/repl/) it works, but the generated JavaScript looks the same as the code generated in the Web VPython environment. The only thing I can think of at the moment to explain this is that perhaps there has been some correction to RapydScript that hasn't made it into Web VPython's use of RapydScript.

**Comment by BruceSherwood** [comment]
I found a strange work-around, which is to add an additional a.pysort() at the end. (I'll mention that Web VPython converts sort to pysort.)

**Comment by joejoe2** [comment]
I have updated the example. Add additional pysort () only works for asc sorting. Maybe you can compare the RapydScript you used with theirs and fix this issue ?

```
Web VPython 3.2

# work for plain list 
a = [6, 4, 5]
a.pysort()
print(a)

# not work for nested list with key
def k(x):
    return x[0]
a = [[6], [4], [5]]
a.pysort(key=k)
print(a)

# workaround
def k(x):
    return x[0]
a = [[6], [4], [5]]
a.pysort(key=k)
a.pysort()
print(a)

# workaround is not work
def k(x):
    return -x[0]
a = [[6], [4], [5]]
a.pysort(key=k)
a.pysort()
print(a)
```

**Comment by BruceSherwood** [comment]
I don't understand why you say that the 4th version does not work. Replacing pysort with sort, so that it can be used using installed Python and vpython module, I find that the 4th version works in both flavors of VPython and also works in the RapydScript-NG REPL. I am puzzled by the 4th version's k function returning -x[0] rather than x[0]. As far as making sort work properly in Web VPython, without the workaround, that is not easy, and I doubt that I can fix this in the near future due to many other responsibilities, and the fact that in 7 years of Web VPython use no one until now reported this bug.

**Comment by joejoe2** [comment]
@BruceSherwood I think i got it. Maybe we have to clarify this in the readme or docs ?
If we use def function like:
```
# not work for nested list with key
def k(x):
    return x[0]
a = [[6], [4], [5]]
a.pysort(key=k)
print(a)
```
k will be compiled to:
```
async function k(x) {
        return ρσ_getitem(x, 0);
};
```
and this async function will be applied before sort on each element, this may cause some problem because the async will return an promise


but if we use anonymous function:
```
k=def (x):
    return x[0]
```
then k will be compiled to:
```
k = (function() {
        var ρσ_anonfunc = function (x) {
            return ρσ_getitem(x, 0);
        };
        if (!ρσ_anonfunc.__argnames__) Object.defineProperties(ρσ_anonfunc, {
            __argnames__ : {value: ["x"]},
            __module__ : {value: null}
        });
        return ρσ_anonfunc;
    })();
```
so the function will return an comparable value

**Comment by joejoe2** [comment]
Or change [this line](https://github.com/vpython/glowscript/blob/7eb4a0abe33e11362f0c1e2e1472b9a41ee3cd68/lib/rapydscript/runtime.js#L896) to handle async and normal functions at the same time
```
keymap.set(k, await Promise.resolve(key(k)));
```

**Comment by BruceSherwood** [comment]
I've updated Web VPython. Many thanks for pointing out that the problem lay with async/await. You can see the changes at https://github.com/vpython/glowscript/commit/edd13d3d5ec546b8caedb364171431c728c75fe8

**Comment by joejoe2** [comment]
Thank you. I have checked the pysort() is workning now.
