### ISSUE TITLE
inputs in glowscript

### ISSUE THREAD

**Issue by Yukti-09** [vpython/glowscript#38]
Is there no way that I could take inputs in glowscript?

**Comment by BruceSherwood** [comment]
https://www.glowscript.org/docs/VPythonDocs/controls.html documents many ways to get input.

**Comment by Yukti-09** [comment]
I'm getting an error on executing that:

https://www.glowscript.org/#/user/YuktiKhosla/folder/MyPrograms/program/ONE/edit

**Comment by BruceSherwood** [comment]
Thanks for for the report. I see that input() works but indeed input(prompt='hello') does not. There also seems to be a problem with winput.

**Comment by BruceSherwood** [comment]
I note that input and winput work if prompt isn't used.

**Comment by BruceSherwood** [comment]
Now fixed in GlowScript 2.9. Thanks again for pointing out the bug.
