### ISSUE TITLE
Error: super is a reserved word

### ISSUE THREAD

**Issue by hmathers** [vpython/glowscript#92]
I tried to call `super().__init__` in a child class and got "Error: super is a reserved word"

**Comment by BruceSherwood** [comment]
Could you please provide a very short program that shows the problem? It
sounds like it could be a bug in the RapydScript-NG Python-to-JavaScript
transpiler.

Bruce

**Comment by hmathers** [comment]
`GlowScript 2.9 VPython

class Ball: pass
class Orb(Ball):
    def __init__(self): super().__init__()
ball = Orb()`

**Comment by BruceSherwood** [comment]
Thanks. I found and fixed a bug in my code, so that if you replace "super()" with "Ball" the program works. As for the use of super(), that does seem to be a RapydScript-NG issue, which I'll report.

**Comment by BruceSherwood** [comment]
Actually, to be compatible with true Python, the statement should be Ball.__init__(self).

As for RapydScript-NG, the response to my question was this: 

"super is not supported in RS as it is a keyword in javascript with different semantics. See
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super"

So RapydScript-NG isn't going to change. There are limits to how close RapydScript-NG (and therefore GlowScript) can go in turning a Python program into a JavaScript program.
